### ISSUE TITLE
Outdated compared to main branch

### ISSUE THREAD

**Issue by FavoritoHJS** [2No2Name/lithium-fabric#1]
**Is your feature request related to a problem? Please describe.**
Not really, though this fork being outdated might make newer Lithium optimizations and HopperOptimizations mutually exclusive.

**Describe the solution you'd like**
Merge newer changes over to the fork.

**Describe alternatives you've considered**
¯\\_o\_/¯

**Additional context**
What other context is necessary?

**Comment by QPCrummer** [comment]
Agreed, maybe even try to compile the unreleased code too.

**Comment by 2No2Name** [comment]
Updated it now
