### ISSUE TITLE
Updating to 1.16.5?

### ISSUE THREAD

**Issue by QPCrummer** [2No2Name/lithium-fabric#2]
I specifically use this fork because I run a fairly large technical Minecraft server. It helps the tps tremendously when by large sorting systems. I wondered if you could update this mod to the latest Lithium version, 0.6.1. Thanks for creating this mod. HopperOptimizations might also have to be updated, I haven’t tested it yet.

**Comment by FavoritoHJS** [comment]
I've tried setting the MC version to >=1.16.4, but it freaks out with lithium-api.

Meanwhile, you can use [DFASCF](https://github.com/alkyaly/DFASCF) or [Dispenser Portal Fix](https://modrinth.com/mod/dispenser-portal-fix) to mod in the main change (fixing the portal bug), and, IIRC, 1.16.5 clients can connect to 1.16.4 servers, but test that beforehand.

**Comment by QPCrummer** [comment]
Yes, but 1.16.5 fixed security issues as well.

**Comment by Croft3r** [comment]
> I've tried setting the MC version to >=1.16.4, but it freaks out with lithium-api.
> 
> Meanwhile, you can use [DFASCF](https://github.com/alkyaly/DFASCF) or [Dispenser Portal Fix](https://modrinth.com/mod/dispenser-portal-fix) to mod in the main change (fixing the portal bug), and, IIRC, 1.16.5 clients can connect to 1.16.4 servers, but test that beforehand.

To resolve that you can actually change the MC version on the API too, this stumped me for a good while. The jar for the API is located in META-INF/jars. But, as always make sure you run plenty of tests and keep VERY frequent backups. While very little seems to have changed between the versions, there can always be a little collateral damage that can cause some strange bugs.

**Comment by DragonEggBedrockBreaking** [comment]
I have [a fork](https://github.com/DragonEggBedrockBreaking/lithium-fabric) that updates 2no2name's fork every time a new commit is added to base lithium (check the 1.16.x/update branch on my fork if you want this, the 1.16.x/more branch is for my testing), but the mod is probably unstable, mostly untested and you have to build it yourself. I would NOT recommend using it for playing, merely as a reference for how I worked around what this fork added to make hopper optimizations work. NOTE AGAIN: DO *NOT* USE MY FORK FOR PLAYING AS IT IS UNSTABLE AND NO GUARANTEES ARE GIVEN!!!

**Comment by QPCrummer** [comment]
As long as it won’t corrupt too much of my world I will use it (;

**Comment by QPCrummer** [comment]
@DragonEggBedrockBreaking Does this fork auto update, or do I have to rebuild it each time? Also, do I have get your HopperOptimizations mod or does the original one work.

**Comment by DragonEggBedrockBreaking** [comment]
> 
> 
> @DragonEggBedrockBreaking Does this fork auto update, or do I have to rebuild it each time? Also, do I have get your HopperOptimizations mod or does the original one work.

1) The fork doesn't auto-update, you need to build it every time. I may start posting releases, but no guarantees.
2) Original HopperOptimizations should work fine.

**Comment by DragonEggBedrockBreaking** [comment]
> 
> 
> As long as it won’t corrupt too much of my world I will use it (;

REMEMBER: NO GUARANTEES ARE GIVEN AND IF IT CORRUPTS YOUR WORLD, I CAN DO VERY LITTLE ABOUT IT. REMEMBER TO TAKE REGULAR BACKUPS.

**Comment by QPCrummer** [comment]
I have scheduled backups every 12hrs, I will definitely use your fork then. Thanks for helping me!

**Comment by DragonEggBedrockBreaking** [comment]
> 
> 
> I have scheduled backups every 12hrs, I will definitely use your fork then. Thanks for helping me!

I'm fine with that, as long as 2no2name doesn't get annoyed...

**Comment by DragonEggBedrockBreaking** [comment]
> 
> 
> @DragonEggBedrockBreaking Does this fork auto update, or do I have to rebuild it each time?

You can probably use GitHub actions now that I activated it. I downgraded the JDK version to 8, so it should work for most ppl.

**Comment by QPCrummer** [comment]
It works, thanks. Constant 20tps is nice.

**Comment by DragonEggBedrockBreaking** [comment]
now this fork has updated, so you no longer have to use my fork
