### ISSUE TITLE
ExtraDoors LandPathNodeMakerMixin conflict

### ISSUE THREAD

**Issue by sm9cc** [2No2Name/lithium-fabric#3]
### Reproduction Steps
Load world with ExtraDoors & this Lithium fork.

### Crash Report File
https://gist.github.com/SM9CC/0f6b919d26564c39221ea6efac664b83

### Additional Information
This issue only seems to happen with your fork of Lithium, problematic code - https://github.com/ExtraCrafTX/ExtraDoors/blob/master/src/main/java/com/extracraftx/minecraft/extradoors/mixin/LandPathNodeMakerMixin.java

**Comment by 2No2Name** [comment]
Work around this by adding `mixin.ai.pathing=false` to the lithium properties
